FROM node:10.16-alpine

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ARG AWS_REGION
ENV AWS_REGION=$AWS_REGION

ADD . /app

WORKDIR /app
RUN npm install
RUN npm run build
RUN npm run deploy:app

EXPOSE 8080

ENTRYPOINT [ "npm", "run", "start" ]
